resolver: lts-17.4

packages:
- '.'
# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- github: lamdu/bindings-freetype-gl
  commit: abcb891cf2ed01edb2d02197ef2b354d6ff43db5
- github: lamdu/graphics-drawingcombinators
  commit: 6253576fdd9233df5c3f43002310f38b0928c2d5
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/FreetypeGL
  commit: d2312f89cdf1412d584d13cda235ef683fa9c832

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

# require-stack-version: ">=2.5"
