resolver: lts-20.20

packages:
- '.'
# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- inline-c-objc-0.1.0.0
- github: lamdu/bindings-freetype-gl
  commit: 8d311d96c5fa7fcfb5b79d057c9c24944d5d234b
- github: lamdu/graphics-drawingcombinators
  commit: 39500dd189b0676468848d1f452ac31c7f0ec461
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/FreetypeGL
  commit: 18ca298d8fd48ad18f75264553b57714bf070c77
- github: lamdu/GLFW-b
  commit: 506abf792cfd98f9a4e6d0bc526b74f848dc413e
- github: lamdu/bindings-GLFW
  commit: 4402c6b6fee81e59f5931fabe1724233cd0ca08c

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

flags:
  bindings-GLFW:
    ExposeNative: true

# require-stack-version: ">=2.5"
